name: Garmin Daily Sync

on:
  #schedule:
    #- cron: '29 7 * * *'
  workflow_dispatch:

jobs:
  garmin_sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # --- ВОССТАНОВЛЕНИЕ СЕССИИ ИЗ СЕКРЕТА (Base64) ---
      - name: Restore Garmin Session
        run: |
          echo "${{ secrets.GARMIN_SESSION_BASE64 }}" | base64 -d | tar -xz || echo "No session found"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install garminconnect gspread google-auth requests garth

      - name: Run main.py
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
